### ISSUE TITLE
Postgres issue: TxIndex Problem attaching block

### ISSUE THREAD

**Issue by tijno** [bitclout/core#102]
After full sync of blocks, postgresql node starts reporting this error:

```
E0824 21:14:44.360203       1 txindex.go:170] tryUpdateTxindex: Problem running update: Update: Problem fetching attach block with hash 00000016c72096930787c7e7de4ad069198c2137feddeecbe6a9ec4d61cb6870: Key not found
I0824 21:14:45.380051       1 txindex.go:270] Update: Updating txindex tip (height: 0, hash: 5567c45b7b83b604f9ff5cb5e88dfc9ad7d5a1dd5818dd19e6d02466f47cbd62) to block tip (height: 54444, hash: 00000000000040ad0b7a1c87854db70e970c06475be2be504879a5fc631f04ed)
```

After a few minutes of this (about 250 errors) - panic occurred. Not sure if related.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb416a7]

goroutine 50 [running]:
github.com/bitclout/core/lib.(*UtxoView).CopyUtxoView(0xc148fa1a40, 0xc00010b140, 0xc14b537eb0, 0x414fc5)
        /bitclout/src/core/lib/block_view.go:1013 +0xd07
github.com/bitclout/core/lib.(*BitCloutMempool).regenerateReadOnlyView(0xc000524000, 0x127cd00, 0xc000524020)
        /bitclout/src/core/lib/mempool.go:1926 +0x47
github.com/bitclout/core/lib.(*BitCloutMempool).RegenerateReadOnlyView(0xc000524000, 0x0, 0x0)
        /bitclout/src/core/lib/mempool.go:1953 +0xa8
github.com/bitclout/core/lib.(*BitCloutMempool).StartReadOnlyUtxoViewRegenerator.func1(0xc000524000)
        /bitclout/src/core/lib/mempool.go:1909 +0x148
created by github.com/bitclout/core/lib.(*BitCloutMempool).StartReadOnlyUtxoViewRegenerator
        /bitclout/src/core/lib/mempool.go:1894 +0xa5
```

Update to latest backend from 7 hours ago (58caa9aacdf0d59cf4270d16617cbce8ea64091f) does not resolve the issue.

Source of issue:
https://github.com/bitclout/core/blob/c2e844140e5b9c1ad67a4a863a17bc1acf622ac0/lib/txindex.go#L370

Hash `00000016c72096930787c7e7de4ad069198c2137feddeecbe6a9ec4d61cb6870` is in the database

![20210825-hI8AeWHK](https://user-images.githubusercontent.com/69529928/130752403-2bf7e87c-7ebe-403a-b0a1-d1759f66ab84.png)

**Comment by maebeam** [comment]
Thanks for the report! I was seeing these issues on our postgres nodes as well. I've merged a fix into main

**Comment by tijno** [comment]
Does it require resync again @maebeam  ?

After pulling new image still seeing the other issue #98 `during attach in reorg: Key not found`

**Comment by maebeam** [comment]
It should not require a resync. I have yet to experience these `reorg` errors.

**Comment by tijno** [comment]
Ah i found that there is an error before that. Ill raise as separate issue.
